[programs.devnet]
myepicproject = "BiwATQbjXu7R4HR83fHoa2Zvuvvw1tktwG3VaKi92jLd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tc/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
